### Create Prometheus Alert Rule
POST {{domain}}/alert-rule/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "test1",
    "type": "prometheus",
    "queryType": "dynamic",
    "dataSourceIds": [],
    "dataSourceAlertName": "prometheusAlertNAme",
    "extraField": [
        {
            "key" : "asd",
            "value" : "adf"
        },
        {
            "key" : "asd",
            "value" : "adf"
        }
    ],
    "queryText": "",
    "queryObject": "",
    "endpoints": [
        "a",
        "b"
    ],
    "accessUsers": [
        "a",
        "b"
    ],
    "tags": []
}

### Create Pmm Alert Rule
POST {{domain}}/alert-rule/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "myPmmAlert",
    "type": "pmm",
    "queryType": "dynamic",
    "dataSourceIds": ["6826d12427f551da450610b2"],
    "dataSourceAlertName": "pmm_mysql_too_manrting Rule",
    "extraField": [],
    "queryText": "",
    "queryObject": "",
    "endpoints": [
    ],
    "accessUsers": [
    ],
    "tags": []
}

### Create API Alert Rule
POST {{domain}}/alert-rule/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "test1",
    "type" : "api",
    "enableAutoResolve": true,
    "autoResolveMinutes" : 5,
    "endpoints": [
        "a",
        "b"
    ],
    "accessUsers": [
        "a",
        "b"
    ],
    "tags": []
}

### Create Notification Alert Rule
POST {{domain}}/alert-rule/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "testNotif",
    "type" : "notification",
    "endpoints": [
    ],
    "accessUsers": [
    ],
    "tags": []
}
