import type { Metadata } from "next";
import { Inter } from "next/font/google";
import localfont from "next/font/local";
import { type PropsWithChildren } from "react";

import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ToastContainer, Zoom } from "react-toastify";

import Wrapper from "@/components/Wrapper";
import { getCurrentDirection } from "@/locales/server";
import Provider from "@/provider";

import "react-toastify/dist/ReactToastify.css";
import "../globals.css";

const inter = Inter({
  weight: ["300", "400", "700"],
  style: ["normal"],
  subsets: ["latin"],
  display: "swap"
});

const vazir = localfont({
  src: [
    { path: "../../../public/static/fonts/Vazir-Bold-FD.woff2", style: "normal", weight: "700" },
    { path: "../../../public/static/fonts/Vazir-FD.woff2", style: "normal", weight: "400" },
    { path: "../../../public/static/fonts/Vazir-Medium-FD.woff2", style: "normal", weight: "300" }
  ]
});

export const metadata: Metadata = {
  title: "Skylogs",
  description: "Generated by Skylogs.io Team"
};

export default async function RootLayout({
  children,
  params: { locale }
}: PropsWithChildren<{ params: { locale: string } }>) {
  const dir = await getCurrentDirection();
  return (
    <html lang={locale} dir={dir}>
      <body className={dir === "ltr" ? inter.className : vazir.className}>
        <AppRouterCacheProvider>
          <Provider locale={locale}>
            <Wrapper>{children}</Wrapper>
          </Provider>
        </AppRouterCacheProvider>
        <ToastContainer
          position={dir === "ltr" ? "bottom-right" : "bottom-left"}
          hideProgressBar
          transition={Zoom}
        />
      </body>
    </html>
  );
}
