GET {{domain}}/endpoint/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}


###
GET {{domain}}/endpoint/indexFlow
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}


###
GET {{domain}}/endpoint/createFlowEndpoints
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}


###
GET {{domain}}/endpoint/680d668e20f7ecb5bc026722
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}


###
// type can be sms , call , teams , telegram  , email , flow
POST {{domain}}/endpoint/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "test1",
    "type" : "sms",
    "value" : "09000000000",
    "isPublic" : false
}

###
// for telegram type body should be like this
POST {{domain}}/endpoint/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "test2",
    "type" : "telegram",
    "value" : "-100",
    "threadId" : "11",
    "botToken" : "",
    "isPublic" : false
}

###
// for flow type body should be like this ,  timeUnit can be s ,m ,h
POST {{domain}}/endpoint/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "test3",
    "type" : "flow",
    "steps" : [
        {
            "type" : "wait",
            "duration" : 15,
            "timeUnit" : "s"
        },
        {
            "type": "endpoint",
            "endpointIds" : [
                "67ab9d887ad723b5b807db12",
                "67ab9d887ad723b5b807db12"
            ]
        },
        {
            "type" : "wait",
            "duration" : 15,
            "timeUnit" : "m"
        },
        {
            "type" : "wait",
            "duration" : 15,
            "timeUnit" : "m"
        },
        {
            "type": "endpoint",
            "endpointIds" : [
                "67ab9d887ad723b5b807db12",
                "67ab9d887ad723b5b807db12"
            ]
        }
    ],
    "isPublic" : false
}

###
PUT {{domain}}/endpoint/67ab9d887ad723b5b807db12
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "test2",
    "type" : "telegram",
    "chatId" : "-100",
    "threadId" : "2",
    "botToken" : "",
    "isPublic" : true
}


###
POST {{domain}}/endpoint/changeOwner/67ab9d887ad723b5b807db12
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "userId": "userId"
}


###
DELETE {{domain}}/endpoint/67ab9d887ad723b5b807db12
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

