GET {{domain}}/status/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}


###
GET {{domain}}/status/67ab9d887ad723b5b807db12
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}


###
GET {{domain}}/status/all
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}


###
POST {{domain}}/status/
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Test",
    "tags" : ["a","b"]
}

###
PUT {{domain}}/status/67ab9d887ad723b5b807db12
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}

{
    "name": "Test",
    "tags" : ["a","b"]
}


###
DELETE {{domain}}/status/67ab9d887ad723b5b807db12
Content-Type: application/json
Accept: application/json
Authorization: Bearer {{authToken}}



